name: Génération quotidienne podcast

on:
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h UTC
  workflow_dispatch:      # Lancement manuel possible

jobs:
  build:
    runs-on: ubuntu-latest
    environment: API_KEY  # ← doit correspondre au nom de ton Environment dans GitHub

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
 
      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter les scripts Python
        run: |
          python main2.py
          python update_rss.py

      - name: Commit et push des fichiers mis à jour
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add podcasts/*.mp3 scripts/*.txt rss.xml script_hier.txt || true
          git commit -m "🎙️ Épisode auto-généré le $(date +'%d-%m-%Y')" || echo "Aucun changement à pousser"
          git push
